/* automatically generated by rust-bindgen 0.72.1 */

pub const ROMX_VERSION_MAJOR: u32 = 0;
pub const ROMX_VERSION_MINOR: u32 = 2;
pub const ROMX_VERSION_PATCH: u32 = 0;
pub const ROMX_VERSION_STRING: &[u8; 6] = b"0.2.0\0";
pub const ROMX_ERROR_MESSAGE_CAPACITY: u32 = 256;
// bindgen interprets UINT64_MAX as a signed sentinel on some hosts.  The C
// ABI declares this value as uint64_t, so keep the generated constant's type
// and value faithful to romx.h.
pub const ROMX_OFFSET_UNKNOWN: u64 = u64::MAX;
pub type romx_result_t = i32;
pub const romx_registry_status_ROMX_REGISTRY_UNSPECIFIED: romx_registry_status = 0;
pub const romx_registry_status_ROMX_REGISTRY_KNOWN: romx_registry_status = 1;
pub const romx_registry_status_ROMX_REGISTRY_UNKNOWN: romx_registry_status = 2;
pub const romx_registry_status_ROMX_REGISTRY_PRIVATE: romx_registry_status = 3;
pub const romx_registry_status_ROMX_REGISTRY_PROHIBITED: romx_registry_status = 4;
pub type romx_registry_status = ::std::os::raw::c_uint;
pub use self::romx_registry_status as romx_registry_status_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_error {
    pub code: romx_result_t,
    pub system_code: i32,
    pub byte_offset: u64,
    pub message: [::std::os::raw::c_char; 256usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_error"][::std::mem::size_of::<romx_error>() - 272usize];
    ["Alignment of romx_error"][::std::mem::align_of::<romx_error>() - 8usize];
    ["Offset of field: romx_error::code"][::std::mem::offset_of!(romx_error, code) - 0usize];
    ["Offset of field: romx_error::system_code"]
        [::std::mem::offset_of!(romx_error, system_code) - 4usize];
    ["Offset of field: romx_error::byte_offset"]
        [::std::mem::offset_of!(romx_error, byte_offset) - 8usize];
    ["Offset of field: romx_error::message"][::std::mem::offset_of!(romx_error, message) - 16usize];
};
pub type romx_error_t = romx_error;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_io {
    pub struct_size: u32,
    pub user_data: *mut ::std::os::raw::c_void,
    pub get_size: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            size: *mut u64,
            error: *mut romx_error_t,
        ) -> romx_result_t,
    >,
    pub read_at: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            offset: u64,
            buffer: *mut ::std::os::raw::c_void,
            size: u64,
            bytes_read: *mut u64,
            error: *mut romx_error_t,
        ) -> romx_result_t,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_io"][::std::mem::size_of::<romx_io>() - 32usize];
    ["Alignment of romx_io"][::std::mem::align_of::<romx_io>() - 8usize];
    ["Offset of field: romx_io::struct_size"]
        [::std::mem::offset_of!(romx_io, struct_size) - 0usize];
    ["Offset of field: romx_io::user_data"][::std::mem::offset_of!(romx_io, user_data) - 8usize];
    ["Offset of field: romx_io::get_size"][::std::mem::offset_of!(romx_io, get_size) - 16usize];
    ["Offset of field: romx_io::read_at"][::std::mem::offset_of!(romx_io, read_at) - 24usize];
};
pub type romx_io_t = romx_io;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_reader_options {
    pub struct_size: u32,
    pub reserved: u32,
    pub max_metadata_size: u64,
    pub max_cover_size: u64,
    pub max_cover_dimension: u32,
    pub io_chunk_size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_reader_options"][::std::mem::size_of::<romx_reader_options>() - 32usize];
    ["Alignment of romx_reader_options"][::std::mem::align_of::<romx_reader_options>() - 8usize];
    ["Offset of field: romx_reader_options::struct_size"]
        [::std::mem::offset_of!(romx_reader_options, struct_size) - 0usize];
    ["Offset of field: romx_reader_options::reserved"]
        [::std::mem::offset_of!(romx_reader_options, reserved) - 4usize];
    ["Offset of field: romx_reader_options::max_metadata_size"]
        [::std::mem::offset_of!(romx_reader_options, max_metadata_size) - 8usize];
    ["Offset of field: romx_reader_options::max_cover_size"]
        [::std::mem::offset_of!(romx_reader_options, max_cover_size) - 16usize];
    ["Offset of field: romx_reader_options::max_cover_dimension"]
        [::std::mem::offset_of!(romx_reader_options, max_cover_dimension) - 24usize];
    ["Offset of field: romx_reader_options::io_chunk_size"]
        [::std::mem::offset_of!(romx_reader_options, io_chunk_size) - 28usize];
};
pub type romx_reader_options_t = romx_reader_options;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_region_info {
    pub offset: u64,
    pub size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_region_info"][::std::mem::size_of::<romx_region_info>() - 16usize];
    ["Alignment of romx_region_info"][::std::mem::align_of::<romx_region_info>() - 8usize];
    ["Offset of field: romx_region_info::offset"]
        [::std::mem::offset_of!(romx_region_info, offset) - 0usize];
    ["Offset of field: romx_region_info::size"]
        [::std::mem::offset_of!(romx_region_info, size) - 8usize];
};
pub type romx_region_info_t = romx_region_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_info {
    pub struct_size: u32,
    pub version: u32,
    pub file_size: u64,
    pub payload: romx_region_info_t,
    pub metadata: romx_region_info_t,
    pub cover: romx_region_info_t,
    pub payload_index: romx_region_info_t,
    pub immutable_padding: romx_region_info_t,
    pub mutable_region: romx_region_info_t,
    pub footer: romx_region_info_t,
    pub immutable_size: u64,
    pub immutable_hash_algorithm: u32,
    pub footer_crc32: u32,
    pub platform_id: u16,
    pub launch_format_id: u16,
    pub entry_count: u32,
    pub entrypoint_index: u32,
    pub immutable_sha256: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_info"][::std::mem::size_of::<romx_info>() - 192usize];
    ["Alignment of romx_info"][::std::mem::align_of::<romx_info>() - 8usize];
    ["Offset of field: romx_info::struct_size"]
        [::std::mem::offset_of!(romx_info, struct_size) - 0usize];
    ["Offset of field: romx_info::version"][::std::mem::offset_of!(romx_info, version) - 4usize];
    ["Offset of field: romx_info::file_size"]
        [::std::mem::offset_of!(romx_info, file_size) - 8usize];
    ["Offset of field: romx_info::payload"][::std::mem::offset_of!(romx_info, payload) - 16usize];
    ["Offset of field: romx_info::metadata"][::std::mem::offset_of!(romx_info, metadata) - 32usize];
    ["Offset of field: romx_info::cover"][::std::mem::offset_of!(romx_info, cover) - 48usize];
    ["Offset of field: romx_info::payload_index"]
        [::std::mem::offset_of!(romx_info, payload_index) - 64usize];
    ["Offset of field: romx_info::immutable_padding"]
        [::std::mem::offset_of!(romx_info, immutable_padding) - 80usize];
    ["Offset of field: romx_info::mutable_region"]
        [::std::mem::offset_of!(romx_info, mutable_region) - 96usize];
    ["Offset of field: romx_info::footer"][::std::mem::offset_of!(romx_info, footer) - 112usize];
    ["Offset of field: romx_info::immutable_size"]
        [::std::mem::offset_of!(romx_info, immutable_size) - 128usize];
    ["Offset of field: romx_info::immutable_hash_algorithm"]
        [::std::mem::offset_of!(romx_info, immutable_hash_algorithm) - 136usize];
    ["Offset of field: romx_info::footer_crc32"]
        [::std::mem::offset_of!(romx_info, footer_crc32) - 140usize];
    ["Offset of field: romx_info::platform_id"]
        [::std::mem::offset_of!(romx_info, platform_id) - 144usize];
    ["Offset of field: romx_info::launch_format_id"]
        [::std::mem::offset_of!(romx_info, launch_format_id) - 146usize];
    ["Offset of field: romx_info::entry_count"]
        [::std::mem::offset_of!(romx_info, entry_count) - 148usize];
    ["Offset of field: romx_info::entrypoint_index"]
        [::std::mem::offset_of!(romx_info, entrypoint_index) - 152usize];
    ["Offset of field: romx_info::immutable_sha256"]
        [::std::mem::offset_of!(romx_info, immutable_sha256) - 156usize];
};
pub type romx_info_t = romx_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_reader {
    _unused: [u8; 0],
}
pub type romx_reader_t = romx_reader;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_metadata {
    _unused: [u8; 0],
}
pub type romx_metadata_t = romx_metadata;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_payload_mapping {
    _unused: [u8; 0],
}
pub type romx_payload_mapping_t = romx_payload_mapping;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_payload_file {
    _unused: [u8; 0],
}
pub type romx_payload_file_t = romx_payload_file;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_vfs_file {
    _unused: [u8; 0],
}
pub type romx_vfs_file_t = romx_vfs_file;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_file {
    _unused: [u8; 0],
}
pub type romx_mutable_file_t = romx_mutable_file;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_bundle {
    _unused: [u8; 0],
}
pub type romx_mutable_bundle_t = romx_mutable_bundle;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_save_catalog {
    _unused: [u8; 0],
}
pub type romx_save_catalog_t = romx_save_catalog;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_probe {
    _unused: [u8; 0],
}
pub type romx_probe_t = romx_probe;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_entry_info {
    pub struct_size: u32,
    pub index: u32,
    pub flags: u32,
    pub format_id: u16,
    pub reserved: u16,
    pub data_offset: u64,
    pub data_size: u64,
    pub crc32: u32,
    pub path_size: u32,
    pub path: [::std::os::raw::c_char; 481usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_entry_info"][::std::mem::size_of::<romx_entry_info>() - 528usize];
    ["Alignment of romx_entry_info"][::std::mem::align_of::<romx_entry_info>() - 8usize];
    ["Offset of field: romx_entry_info::struct_size"]
        [::std::mem::offset_of!(romx_entry_info, struct_size) - 0usize];
    ["Offset of field: romx_entry_info::index"]
        [::std::mem::offset_of!(romx_entry_info, index) - 4usize];
    ["Offset of field: romx_entry_info::flags"]
        [::std::mem::offset_of!(romx_entry_info, flags) - 8usize];
    ["Offset of field: romx_entry_info::format_id"]
        [::std::mem::offset_of!(romx_entry_info, format_id) - 12usize];
    ["Offset of field: romx_entry_info::reserved"]
        [::std::mem::offset_of!(romx_entry_info, reserved) - 14usize];
    ["Offset of field: romx_entry_info::data_offset"]
        [::std::mem::offset_of!(romx_entry_info, data_offset) - 16usize];
    ["Offset of field: romx_entry_info::data_size"]
        [::std::mem::offset_of!(romx_entry_info, data_size) - 24usize];
    ["Offset of field: romx_entry_info::crc32"]
        [::std::mem::offset_of!(romx_entry_info, crc32) - 32usize];
    ["Offset of field: romx_entry_info::path_size"]
        [::std::mem::offset_of!(romx_entry_info, path_size) - 36usize];
    ["Offset of field: romx_entry_info::path"]
        [::std::mem::offset_of!(romx_entry_info, path) - 40usize];
};
pub type romx_entry_info_t = romx_entry_info;
pub type romx_mutable_status_t = i32;
pub type romx_mutable_namespace_t = u16;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_object_info {
    pub struct_size: u32,
    pub slot_index: u32,
    pub object_namespace: romx_mutable_namespace_t,
    pub reserved: u16,
    pub data_offset: u64,
    pub data_capacity: u64,
    pub data_size: u64,
    pub generation: u64,
    pub modified_unix_seconds: u64,
    pub data_crc32: u32,
    pub key_size: u32,
    pub key: [::std::os::raw::c_char; 449usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_mutable_object_info"]
        [::std::mem::size_of::<romx_mutable_object_info>() - 520usize];
    ["Alignment of romx_mutable_object_info"]
        [::std::mem::align_of::<romx_mutable_object_info>() - 8usize];
    ["Offset of field: romx_mutable_object_info::struct_size"]
        [::std::mem::offset_of!(romx_mutable_object_info, struct_size) - 0usize];
    ["Offset of field: romx_mutable_object_info::slot_index"]
        [::std::mem::offset_of!(romx_mutable_object_info, slot_index) - 4usize];
    ["Offset of field: romx_mutable_object_info::object_namespace"]
        [::std::mem::offset_of!(romx_mutable_object_info, object_namespace) - 8usize];
    ["Offset of field: romx_mutable_object_info::reserved"]
        [::std::mem::offset_of!(romx_mutable_object_info, reserved) - 10usize];
    ["Offset of field: romx_mutable_object_info::data_offset"]
        [::std::mem::offset_of!(romx_mutable_object_info, data_offset) - 16usize];
    ["Offset of field: romx_mutable_object_info::data_capacity"]
        [::std::mem::offset_of!(romx_mutable_object_info, data_capacity) - 24usize];
    ["Offset of field: romx_mutable_object_info::data_size"]
        [::std::mem::offset_of!(romx_mutable_object_info, data_size) - 32usize];
    ["Offset of field: romx_mutable_object_info::generation"]
        [::std::mem::offset_of!(romx_mutable_object_info, generation) - 40usize];
    ["Offset of field: romx_mutable_object_info::modified_unix_seconds"]
        [::std::mem::offset_of!(romx_mutable_object_info, modified_unix_seconds) - 48usize];
    ["Offset of field: romx_mutable_object_info::data_crc32"]
        [::std::mem::offset_of!(romx_mutable_object_info, data_crc32) - 56usize];
    ["Offset of field: romx_mutable_object_info::key_size"]
        [::std::mem::offset_of!(romx_mutable_object_info, key_size) - 60usize];
    ["Offset of field: romx_mutable_object_info::key"]
        [::std::mem::offset_of!(romx_mutable_object_info, key) - 64usize];
};
pub type romx_mutable_object_info_t = romx_mutable_object_info;
pub type romx_region_t = i32;
pub type romx_payload_file_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_payload_file_options {
    pub struct_size: u32,
    pub flags: romx_payload_file_flags_t,
    pub reserved: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_payload_file_options"]
        [::std::mem::size_of::<romx_payload_file_options>() - 12usize];
    ["Alignment of romx_payload_file_options"]
        [::std::mem::align_of::<romx_payload_file_options>() - 4usize];
    ["Offset of field: romx_payload_file_options::struct_size"]
        [::std::mem::offset_of!(romx_payload_file_options, struct_size) - 0usize];
    ["Offset of field: romx_payload_file_options::flags"]
        [::std::mem::offset_of!(romx_payload_file_options, flags) - 4usize];
    ["Offset of field: romx_payload_file_options::reserved"]
        [::std::mem::offset_of!(romx_payload_file_options, reserved) - 8usize];
};
pub type romx_payload_file_options_t = romx_payload_file_options;
pub type romx_payload_seek_position_t = i32;
pub type romx_validate_flags_t = u32;
pub type romx_validation_status_t = i32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_validation_report {
    pub struct_size: u32,
    pub structure: romx_validation_status_t,
    pub payload_hashes: romx_validation_status_t,
    pub immutable_sha256: romx_validation_status_t,
    pub metadata: romx_validation_status_t,
    pub cover: romx_validation_status_t,
    pub cover_hashes: romx_validation_status_t,
    pub metadata_result: romx_result_t,
    pub cover_result: romx_result_t,
    pub computed_payload_crc32: u32,
    pub computed_payload_sha256: [u8; 32usize],
    pub computed_immutable_sha256: [u8; 32usize],
    pub computed_cover_sha256: [u8; 32usize],
    pub cover_width: u32,
    pub cover_height: u32,
    pub entry_crc32: romx_validation_status_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_validation_report"][::std::mem::size_of::<romx_validation_report>() - 148usize];
    ["Alignment of romx_validation_report"]
        [::std::mem::align_of::<romx_validation_report>() - 4usize];
    ["Offset of field: romx_validation_report::struct_size"]
        [::std::mem::offset_of!(romx_validation_report, struct_size) - 0usize];
    ["Offset of field: romx_validation_report::structure"]
        [::std::mem::offset_of!(romx_validation_report, structure) - 4usize];
    ["Offset of field: romx_validation_report::payload_hashes"]
        [::std::mem::offset_of!(romx_validation_report, payload_hashes) - 8usize];
    ["Offset of field: romx_validation_report::immutable_sha256"]
        [::std::mem::offset_of!(romx_validation_report, immutable_sha256) - 12usize];
    ["Offset of field: romx_validation_report::metadata"]
        [::std::mem::offset_of!(romx_validation_report, metadata) - 16usize];
    ["Offset of field: romx_validation_report::cover"]
        [::std::mem::offset_of!(romx_validation_report, cover) - 20usize];
    ["Offset of field: romx_validation_report::cover_hashes"]
        [::std::mem::offset_of!(romx_validation_report, cover_hashes) - 24usize];
    ["Offset of field: romx_validation_report::metadata_result"]
        [::std::mem::offset_of!(romx_validation_report, metadata_result) - 28usize];
    ["Offset of field: romx_validation_report::cover_result"]
        [::std::mem::offset_of!(romx_validation_report, cover_result) - 32usize];
    ["Offset of field: romx_validation_report::computed_payload_crc32"]
        [::std::mem::offset_of!(romx_validation_report, computed_payload_crc32) - 36usize];
    ["Offset of field: romx_validation_report::computed_payload_sha256"]
        [::std::mem::offset_of!(romx_validation_report, computed_payload_sha256) - 40usize];
    ["Offset of field: romx_validation_report::computed_immutable_sha256"]
        [::std::mem::offset_of!(romx_validation_report, computed_immutable_sha256) - 72usize];
    ["Offset of field: romx_validation_report::computed_cover_sha256"]
        [::std::mem::offset_of!(romx_validation_report, computed_cover_sha256) - 104usize];
    ["Offset of field: romx_validation_report::cover_width"]
        [::std::mem::offset_of!(romx_validation_report, cover_width) - 136usize];
    ["Offset of field: romx_validation_report::cover_height"]
        [::std::mem::offset_of!(romx_validation_report, cover_height) - 140usize];
    ["Offset of field: romx_validation_report::entry_crc32"]
        [::std::mem::offset_of!(romx_validation_report, entry_crc32) - 144usize];
};
pub type romx_validation_report_t = romx_validation_report;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_sink {
    pub struct_size: u32,
    pub user_data: *mut ::std::os::raw::c_void,
    pub write: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            data: *const ::std::os::raw::c_void,
            size: u64,
            error: *mut romx_error_t,
        ) -> romx_result_t,
    >,
    pub flush: ::std::option::Option<
        unsafe extern "C" fn(
            user_data: *mut ::std::os::raw::c_void,
            error: *mut romx_error_t,
        ) -> romx_result_t,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_sink"][::std::mem::size_of::<romx_sink>() - 32usize];
    ["Alignment of romx_sink"][::std::mem::align_of::<romx_sink>() - 8usize];
    ["Offset of field: romx_sink::struct_size"]
        [::std::mem::offset_of!(romx_sink, struct_size) - 0usize];
    ["Offset of field: romx_sink::user_data"]
        [::std::mem::offset_of!(romx_sink, user_data) - 8usize];
    ["Offset of field: romx_sink::write"][::std::mem::offset_of!(romx_sink, write) - 16usize];
    ["Offset of field: romx_sink::flush"][::std::mem::offset_of!(romx_sink, flush) - 24usize];
};
pub type romx_sink_t = romx_sink;
pub type romx_extract_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_extract_options {
    pub struct_size: u32,
    pub flags: romx_extract_flags_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_extract_options"][::std::mem::size_of::<romx_extract_options>() - 8usize];
    ["Alignment of romx_extract_options"][::std::mem::align_of::<romx_extract_options>() - 4usize];
    ["Offset of field: romx_extract_options::struct_size"]
        [::std::mem::offset_of!(romx_extract_options, struct_size) - 0usize];
    ["Offset of field: romx_extract_options::flags"]
        [::std::mem::offset_of!(romx_extract_options, flags) - 4usize];
};
pub type romx_extract_options_t = romx_extract_options;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_cover_info {
    pub struct_size: u32,
    pub width: u32,
    pub height: u32,
    pub size: u64,
    pub sha256: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_cover_info"][::std::mem::size_of::<romx_cover_info>() - 56usize];
    ["Alignment of romx_cover_info"][::std::mem::align_of::<romx_cover_info>() - 8usize];
    ["Offset of field: romx_cover_info::struct_size"]
        [::std::mem::offset_of!(romx_cover_info, struct_size) - 0usize];
    ["Offset of field: romx_cover_info::width"]
        [::std::mem::offset_of!(romx_cover_info, width) - 4usize];
    ["Offset of field: romx_cover_info::height"]
        [::std::mem::offset_of!(romx_cover_info, height) - 8usize];
    ["Offset of field: romx_cover_info::size"]
        [::std::mem::offset_of!(romx_cover_info, size) - 16usize];
    ["Offset of field: romx_cover_info::sha256"]
        [::std::mem::offset_of!(romx_cover_info, sha256) - 24usize];
};
pub type romx_cover_info_t = romx_cover_info;
pub type romx_writer_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_writer_io_entry {
    pub struct_size: u32,
    pub flags: u32,
    pub virtual_path: *const ::std::os::raw::c_char,
    pub source: *const romx_io_t,
    pub format_id: u16,
    pub reserved: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_writer_io_entry"][::std::mem::size_of::<romx_writer_io_entry>() - 32usize];
    ["Alignment of romx_writer_io_entry"][::std::mem::align_of::<romx_writer_io_entry>() - 8usize];
    ["Offset of field: romx_writer_io_entry::struct_size"]
        [::std::mem::offset_of!(romx_writer_io_entry, struct_size) - 0usize];
    ["Offset of field: romx_writer_io_entry::flags"]
        [::std::mem::offset_of!(romx_writer_io_entry, flags) - 4usize];
    ["Offset of field: romx_writer_io_entry::virtual_path"]
        [::std::mem::offset_of!(romx_writer_io_entry, virtual_path) - 8usize];
    ["Offset of field: romx_writer_io_entry::source"]
        [::std::mem::offset_of!(romx_writer_io_entry, source) - 16usize];
    ["Offset of field: romx_writer_io_entry::format_id"]
        [::std::mem::offset_of!(romx_writer_io_entry, format_id) - 24usize];
    ["Offset of field: romx_writer_io_entry::reserved"]
        [::std::mem::offset_of!(romx_writer_io_entry, reserved) - 26usize];
};
pub type romx_writer_io_entry_t = romx_writer_io_entry;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_writer_path_entry {
    pub struct_size: u32,
    pub flags: u32,
    pub virtual_path: *const ::std::os::raw::c_char,
    pub source_path: *const ::std::os::raw::c_char,
    pub format_id: u16,
    pub reserved: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_writer_path_entry"][::std::mem::size_of::<romx_writer_path_entry>() - 32usize];
    ["Alignment of romx_writer_path_entry"]
        [::std::mem::align_of::<romx_writer_path_entry>() - 8usize];
    ["Offset of field: romx_writer_path_entry::struct_size"]
        [::std::mem::offset_of!(romx_writer_path_entry, struct_size) - 0usize];
    ["Offset of field: romx_writer_path_entry::flags"]
        [::std::mem::offset_of!(romx_writer_path_entry, flags) - 4usize];
    ["Offset of field: romx_writer_path_entry::virtual_path"]
        [::std::mem::offset_of!(romx_writer_path_entry, virtual_path) - 8usize];
    ["Offset of field: romx_writer_path_entry::source_path"]
        [::std::mem::offset_of!(romx_writer_path_entry, source_path) - 16usize];
    ["Offset of field: romx_writer_path_entry::format_id"]
        [::std::mem::offset_of!(romx_writer_path_entry, format_id) - 24usize];
    ["Offset of field: romx_writer_path_entry::reserved"]
        [::std::mem::offset_of!(romx_writer_path_entry, reserved) - 26usize];
};
pub type romx_writer_path_entry_t = romx_writer_path_entry;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_writer_options {
    pub struct_size: u32,
    pub flags: romx_writer_flags_t,
    pub platform_id: u16,
    pub launch_format_id: u16,
    pub mutable_capacity: u64,
    pub mutable_entry_capacity: u32,
    pub max_metadata_size: u64,
    pub max_cover_size: u64,
    pub max_cover_dimension: u32,
    pub io_chunk_size: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_writer_options"][::std::mem::size_of::<romx_writer_options>() - 56usize];
    ["Alignment of romx_writer_options"][::std::mem::align_of::<romx_writer_options>() - 8usize];
    ["Offset of field: romx_writer_options::struct_size"]
        [::std::mem::offset_of!(romx_writer_options, struct_size) - 0usize];
    ["Offset of field: romx_writer_options::flags"]
        [::std::mem::offset_of!(romx_writer_options, flags) - 4usize];
    ["Offset of field: romx_writer_options::platform_id"]
        [::std::mem::offset_of!(romx_writer_options, platform_id) - 8usize];
    ["Offset of field: romx_writer_options::launch_format_id"]
        [::std::mem::offset_of!(romx_writer_options, launch_format_id) - 10usize];
    ["Offset of field: romx_writer_options::mutable_capacity"]
        [::std::mem::offset_of!(romx_writer_options, mutable_capacity) - 16usize];
    ["Offset of field: romx_writer_options::mutable_entry_capacity"]
        [::std::mem::offset_of!(romx_writer_options, mutable_entry_capacity) - 24usize];
    ["Offset of field: romx_writer_options::max_metadata_size"]
        [::std::mem::offset_of!(romx_writer_options, max_metadata_size) - 32usize];
    ["Offset of field: romx_writer_options::max_cover_size"]
        [::std::mem::offset_of!(romx_writer_options, max_cover_size) - 40usize];
    ["Offset of field: romx_writer_options::max_cover_dimension"]
        [::std::mem::offset_of!(romx_writer_options, max_cover_dimension) - 48usize];
    ["Offset of field: romx_writer_options::io_chunk_size"]
        [::std::mem::offset_of!(romx_writer_options, io_chunk_size) - 52usize];
};
pub type romx_writer_options_t = romx_writer_options;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_writer_report {
    pub struct_size: u32,
    pub file_size: u64,
    pub payload_size: u64,
    pub payload_index_size: u64,
    pub metadata_size: u64,
    pub cover_size: u64,
    pub immutable_padding_size: u64,
    pub mutable_capacity: u64,
    pub entry_count: u32,
    pub immutable_hash_algorithm: u32,
    pub immutable_sha256: [u8; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_writer_report"][::std::mem::size_of::<romx_writer_report>() - 104usize];
    ["Alignment of romx_writer_report"][::std::mem::align_of::<romx_writer_report>() - 8usize];
    ["Offset of field: romx_writer_report::struct_size"]
        [::std::mem::offset_of!(romx_writer_report, struct_size) - 0usize];
    ["Offset of field: romx_writer_report::file_size"]
        [::std::mem::offset_of!(romx_writer_report, file_size) - 8usize];
    ["Offset of field: romx_writer_report::payload_size"]
        [::std::mem::offset_of!(romx_writer_report, payload_size) - 16usize];
    ["Offset of field: romx_writer_report::payload_index_size"]
        [::std::mem::offset_of!(romx_writer_report, payload_index_size) - 24usize];
    ["Offset of field: romx_writer_report::metadata_size"]
        [::std::mem::offset_of!(romx_writer_report, metadata_size) - 32usize];
    ["Offset of field: romx_writer_report::cover_size"]
        [::std::mem::offset_of!(romx_writer_report, cover_size) - 40usize];
    ["Offset of field: romx_writer_report::immutable_padding_size"]
        [::std::mem::offset_of!(romx_writer_report, immutable_padding_size) - 48usize];
    ["Offset of field: romx_writer_report::mutable_capacity"]
        [::std::mem::offset_of!(romx_writer_report, mutable_capacity) - 56usize];
    ["Offset of field: romx_writer_report::entry_count"]
        [::std::mem::offset_of!(romx_writer_report, entry_count) - 64usize];
    ["Offset of field: romx_writer_report::immutable_hash_algorithm"]
        [::std::mem::offset_of!(romx_writer_report, immutable_hash_algorithm) - 68usize];
    ["Offset of field: romx_writer_report::immutable_sha256"]
        [::std::mem::offset_of!(romx_writer_report, immutable_sha256) - 72usize];
};
pub type romx_writer_report_t = romx_writer_report;
pub type romx_probe_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_probe_info {
    pub struct_size: u32,
    pub flags: romx_probe_flags_t,
    pub platform_id: u16,
    pub format_id: u16,
    pub cover_size: u64,
    pub name: [::std::os::raw::c_char; 513usize],
    pub serial: [::std::os::raw::c_char; 129usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_probe_info"][::std::mem::size_of::<romx_probe_info>() - 672usize];
    ["Alignment of romx_probe_info"][::std::mem::align_of::<romx_probe_info>() - 8usize];
    ["Offset of field: romx_probe_info::struct_size"]
        [::std::mem::offset_of!(romx_probe_info, struct_size) - 0usize];
    ["Offset of field: romx_probe_info::flags"]
        [::std::mem::offset_of!(romx_probe_info, flags) - 4usize];
    ["Offset of field: romx_probe_info::platform_id"]
        [::std::mem::offset_of!(romx_probe_info, platform_id) - 8usize];
    ["Offset of field: romx_probe_info::format_id"]
        [::std::mem::offset_of!(romx_probe_info, format_id) - 10usize];
    ["Offset of field: romx_probe_info::cover_size"]
        [::std::mem::offset_of!(romx_probe_info, cover_size) - 16usize];
    ["Offset of field: romx_probe_info::name"]
        [::std::mem::offset_of!(romx_probe_info, name) - 24usize];
    ["Offset of field: romx_probe_info::serial"]
        [::std::mem::offset_of!(romx_probe_info, serial) - 537usize];
};
pub type romx_probe_info_t = romx_probe_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_write_options {
    pub struct_size: u32,
    pub flags: u32,
    pub data_capacity: u64,
    pub modified_unix_seconds: u64,
    pub io_chunk_size: u32,
    pub reserved: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_mutable_write_options"]
        [::std::mem::size_of::<romx_mutable_write_options>() - 32usize];
    ["Alignment of romx_mutable_write_options"]
        [::std::mem::align_of::<romx_mutable_write_options>() - 8usize];
    ["Offset of field: romx_mutable_write_options::struct_size"]
        [::std::mem::offset_of!(romx_mutable_write_options, struct_size) - 0usize];
    ["Offset of field: romx_mutable_write_options::flags"]
        [::std::mem::offset_of!(romx_mutable_write_options, flags) - 4usize];
    ["Offset of field: romx_mutable_write_options::data_capacity"]
        [::std::mem::offset_of!(romx_mutable_write_options, data_capacity) - 8usize];
    ["Offset of field: romx_mutable_write_options::modified_unix_seconds"]
        [::std::mem::offset_of!(romx_mutable_write_options, modified_unix_seconds) - 16usize];
    ["Offset of field: romx_mutable_write_options::io_chunk_size"]
        [::std::mem::offset_of!(romx_mutable_write_options, io_chunk_size) - 24usize];
    ["Offset of field: romx_mutable_write_options::reserved"]
        [::std::mem::offset_of!(romx_mutable_write_options, reserved) - 28usize];
};
pub type romx_mutable_write_options_t = romx_mutable_write_options;
pub type romx_save_scan_flags_t = u32;
pub type romx_save_grouping_t = u16;
pub type romx_save_scope_t = u16;
pub type romx_save_source_format_t = u16;
pub type romx_save_candidate_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_save_profile_info {
    pub struct_size: u32,
    pub platform_id: u16,
    pub format_id: u16,
    pub launch_format_id: u16,
    pub grouping: romx_save_grouping_t,
    pub flags: u32,
    pub marker_size: u32,
    pub marker: [::std::os::raw::c_char; 1025usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_save_profile_info"][::std::mem::size_of::<romx_save_profile_info>() - 1048usize];
    ["Alignment of romx_save_profile_info"]
        [::std::mem::align_of::<romx_save_profile_info>() - 4usize];
    ["Offset of field: romx_save_profile_info::struct_size"]
        [::std::mem::offset_of!(romx_save_profile_info, struct_size) - 0usize];
    ["Offset of field: romx_save_profile_info::platform_id"]
        [::std::mem::offset_of!(romx_save_profile_info, platform_id) - 4usize];
    ["Offset of field: romx_save_profile_info::format_id"]
        [::std::mem::offset_of!(romx_save_profile_info, format_id) - 6usize];
    ["Offset of field: romx_save_profile_info::launch_format_id"]
        [::std::mem::offset_of!(romx_save_profile_info, launch_format_id) - 8usize];
    ["Offset of field: romx_save_profile_info::grouping"]
        [::std::mem::offset_of!(romx_save_profile_info, grouping) - 10usize];
    ["Offset of field: romx_save_profile_info::flags"]
        [::std::mem::offset_of!(romx_save_profile_info, flags) - 12usize];
    ["Offset of field: romx_save_profile_info::marker_size"]
        [::std::mem::offset_of!(romx_save_profile_info, marker_size) - 16usize];
    ["Offset of field: romx_save_profile_info::marker"]
        [::std::mem::offset_of!(romx_save_profile_info, marker) - 20usize];
};
pub type romx_save_profile_info_t = romx_save_profile_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_save_scan_options {
    pub struct_size: u32,
    pub flags: romx_save_scan_flags_t,
    pub platform_id: u16,
    pub format_id: u16,
    pub launch_format_id: u16,
    pub source_format_hint: romx_save_source_format_t,
    pub max_candidate_count: u32,
    pub max_file_count: u32,
    pub max_total_size: u64,
    pub max_depth: u32,
    pub reserved: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_save_scan_options"][::std::mem::size_of::<romx_save_scan_options>() - 40usize];
    ["Alignment of romx_save_scan_options"]
        [::std::mem::align_of::<romx_save_scan_options>() - 8usize];
    ["Offset of field: romx_save_scan_options::struct_size"]
        [::std::mem::offset_of!(romx_save_scan_options, struct_size) - 0usize];
    ["Offset of field: romx_save_scan_options::flags"]
        [::std::mem::offset_of!(romx_save_scan_options, flags) - 4usize];
    ["Offset of field: romx_save_scan_options::platform_id"]
        [::std::mem::offset_of!(romx_save_scan_options, platform_id) - 8usize];
    ["Offset of field: romx_save_scan_options::format_id"]
        [::std::mem::offset_of!(romx_save_scan_options, format_id) - 10usize];
    ["Offset of field: romx_save_scan_options::launch_format_id"]
        [::std::mem::offset_of!(romx_save_scan_options, launch_format_id) - 12usize];
    ["Offset of field: romx_save_scan_options::source_format_hint"]
        [::std::mem::offset_of!(romx_save_scan_options, source_format_hint) - 14usize];
    ["Offset of field: romx_save_scan_options::max_candidate_count"]
        [::std::mem::offset_of!(romx_save_scan_options, max_candidate_count) - 16usize];
    ["Offset of field: romx_save_scan_options::max_file_count"]
        [::std::mem::offset_of!(romx_save_scan_options, max_file_count) - 20usize];
    ["Offset of field: romx_save_scan_options::max_total_size"]
        [::std::mem::offset_of!(romx_save_scan_options, max_total_size) - 24usize];
    ["Offset of field: romx_save_scan_options::max_depth"]
        [::std::mem::offset_of!(romx_save_scan_options, max_depth) - 32usize];
    ["Offset of field: romx_save_scan_options::reserved"]
        [::std::mem::offset_of!(romx_save_scan_options, reserved) - 36usize];
};
pub type romx_save_scan_options_t = romx_save_scan_options;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_save_candidate_info {
    pub struct_size: u32,
    pub index: u32,
    pub flags: romx_save_candidate_flags_t,
    pub source_format: romx_save_source_format_t,
    pub grouping: romx_save_grouping_t,
    pub reserved: u16,
    pub scope: romx_save_scope_t,
    pub file_count: u32,
    pub data_size: u64,
    pub key_size: u32,
    pub display_name_size: u32,
    pub title_id_size: u32,
    pub key: [::std::os::raw::c_char; 449usize],
    pub display_name: [::std::os::raw::c_char; 1025usize],
    pub title_id: [::std::os::raw::c_char; 17usize],
    pub extdata_id_size: u32,
    pub extdata_id: [::std::os::raw::c_char; 17usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_save_candidate_info"]
        [::std::mem::size_of::<romx_save_candidate_info>() - 1560usize];
    ["Alignment of romx_save_candidate_info"]
        [::std::mem::align_of::<romx_save_candidate_info>() - 8usize];
    ["Offset of field: romx_save_candidate_info::struct_size"]
        [::std::mem::offset_of!(romx_save_candidate_info, struct_size) - 0usize];
    ["Offset of field: romx_save_candidate_info::index"]
        [::std::mem::offset_of!(romx_save_candidate_info, index) - 4usize];
    ["Offset of field: romx_save_candidate_info::flags"]
        [::std::mem::offset_of!(romx_save_candidate_info, flags) - 8usize];
    ["Offset of field: romx_save_candidate_info::source_format"]
        [::std::mem::offset_of!(romx_save_candidate_info, source_format) - 12usize];
    ["Offset of field: romx_save_candidate_info::grouping"]
        [::std::mem::offset_of!(romx_save_candidate_info, grouping) - 14usize];
    ["Offset of field: romx_save_candidate_info::reserved"]
        [::std::mem::offset_of!(romx_save_candidate_info, reserved) - 16usize];
    ["Offset of field: romx_save_candidate_info::scope"]
        [::std::mem::offset_of!(romx_save_candidate_info, scope) - 18usize];
    ["Offset of field: romx_save_candidate_info::file_count"]
        [::std::mem::offset_of!(romx_save_candidate_info, file_count) - 20usize];
    ["Offset of field: romx_save_candidate_info::data_size"]
        [::std::mem::offset_of!(romx_save_candidate_info, data_size) - 24usize];
    ["Offset of field: romx_save_candidate_info::key_size"]
        [::std::mem::offset_of!(romx_save_candidate_info, key_size) - 32usize];
    ["Offset of field: romx_save_candidate_info::display_name_size"]
        [::std::mem::offset_of!(romx_save_candidate_info, display_name_size) - 36usize];
    ["Offset of field: romx_save_candidate_info::title_id_size"]
        [::std::mem::offset_of!(romx_save_candidate_info, title_id_size) - 40usize];
    ["Offset of field: romx_save_candidate_info::key"]
        [::std::mem::offset_of!(romx_save_candidate_info, key) - 44usize];
    ["Offset of field: romx_save_candidate_info::display_name"]
        [::std::mem::offset_of!(romx_save_candidate_info, display_name) - 493usize];
    ["Offset of field: romx_save_candidate_info::title_id"]
        [::std::mem::offset_of!(romx_save_candidate_info, title_id) - 1518usize];
    ["Offset of field: romx_save_candidate_info::extdata_id_size"]
        [::std::mem::offset_of!(romx_save_candidate_info, extdata_id_size) - 1536usize];
    ["Offset of field: romx_save_candidate_info::extdata_id"]
        [::std::mem::offset_of!(romx_save_candidate_info, extdata_id) - 1540usize];
};
pub type romx_save_candidate_info_t = romx_save_candidate_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_save_file_info {
    pub struct_size: u32,
    pub index: u32,
    pub data_size: u64,
    pub flags: u32,
    pub path_size: u32,
    pub path: [::std::os::raw::c_char; 1025usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_save_file_info"][::std::mem::size_of::<romx_save_file_info>() - 1056usize];
    ["Alignment of romx_save_file_info"][::std::mem::align_of::<romx_save_file_info>() - 8usize];
    ["Offset of field: romx_save_file_info::struct_size"]
        [::std::mem::offset_of!(romx_save_file_info, struct_size) - 0usize];
    ["Offset of field: romx_save_file_info::index"]
        [::std::mem::offset_of!(romx_save_file_info, index) - 4usize];
    ["Offset of field: romx_save_file_info::data_size"]
        [::std::mem::offset_of!(romx_save_file_info, data_size) - 8usize];
    ["Offset of field: romx_save_file_info::flags"]
        [::std::mem::offset_of!(romx_save_file_info, flags) - 16usize];
    ["Offset of field: romx_save_file_info::path_size"]
        [::std::mem::offset_of!(romx_save_file_info, path_size) - 20usize];
    ["Offset of field: romx_save_file_info::path"]
        [::std::mem::offset_of!(romx_save_file_info, path) - 24usize];
};
pub type romx_save_file_info_t = romx_save_file_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_bundle_path_entry {
    pub struct_size: u32,
    pub reserved: u32,
    pub relative_path: *const ::std::os::raw::c_char,
    pub source_path: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_mutable_bundle_path_entry"]
        [::std::mem::size_of::<romx_mutable_bundle_path_entry>() - 24usize];
    ["Alignment of romx_mutable_bundle_path_entry"]
        [::std::mem::align_of::<romx_mutable_bundle_path_entry>() - 8usize];
    ["Offset of field: romx_mutable_bundle_path_entry::struct_size"]
        [::std::mem::offset_of!(romx_mutable_bundle_path_entry, struct_size) - 0usize];
    ["Offset of field: romx_mutable_bundle_path_entry::reserved"]
        [::std::mem::offset_of!(romx_mutable_bundle_path_entry, reserved) - 4usize];
    ["Offset of field: romx_mutable_bundle_path_entry::relative_path"]
        [::std::mem::offset_of!(romx_mutable_bundle_path_entry, relative_path) - 8usize];
    ["Offset of field: romx_mutable_bundle_path_entry::source_path"]
        [::std::mem::offset_of!(romx_mutable_bundle_path_entry, source_path) - 16usize];
};
pub type romx_mutable_bundle_path_entry_t = romx_mutable_bundle_path_entry;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_bundle_options {
    pub struct_size: u32,
    pub flags: u32,
    pub max_entry_count: u32,
    pub max_path_size: u32,
    pub max_bundle_size: u64,
    pub io_chunk_size: u32,
    pub reserved: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_mutable_bundle_options"]
        [::std::mem::size_of::<romx_mutable_bundle_options>() - 32usize];
    ["Alignment of romx_mutable_bundle_options"]
        [::std::mem::align_of::<romx_mutable_bundle_options>() - 8usize];
    ["Offset of field: romx_mutable_bundle_options::struct_size"]
        [::std::mem::offset_of!(romx_mutable_bundle_options, struct_size) - 0usize];
    ["Offset of field: romx_mutable_bundle_options::flags"]
        [::std::mem::offset_of!(romx_mutable_bundle_options, flags) - 4usize];
    ["Offset of field: romx_mutable_bundle_options::max_entry_count"]
        [::std::mem::offset_of!(romx_mutable_bundle_options, max_entry_count) - 8usize];
    ["Offset of field: romx_mutable_bundle_options::max_path_size"]
        [::std::mem::offset_of!(romx_mutable_bundle_options, max_path_size) - 12usize];
    ["Offset of field: romx_mutable_bundle_options::max_bundle_size"]
        [::std::mem::offset_of!(romx_mutable_bundle_options, max_bundle_size) - 16usize];
    ["Offset of field: romx_mutable_bundle_options::io_chunk_size"]
        [::std::mem::offset_of!(romx_mutable_bundle_options, io_chunk_size) - 24usize];
    ["Offset of field: romx_mutable_bundle_options::reserved"]
        [::std::mem::offset_of!(romx_mutable_bundle_options, reserved) - 28usize];
};
pub type romx_mutable_bundle_options_t = romx_mutable_bundle_options;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_bundle_entry_info {
    pub struct_size: u32,
    pub index: u32,
    pub data_size: u64,
    pub data_crc32: u32,
    pub path_size: u32,
    pub path: [::std::os::raw::c_char; 1025usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_mutable_bundle_entry_info"]
        [::std::mem::size_of::<romx_mutable_bundle_entry_info>() - 1056usize];
    ["Alignment of romx_mutable_bundle_entry_info"]
        [::std::mem::align_of::<romx_mutable_bundle_entry_info>() - 8usize];
    ["Offset of field: romx_mutable_bundle_entry_info::struct_size"]
        [::std::mem::offset_of!(romx_mutable_bundle_entry_info, struct_size) - 0usize];
    ["Offset of field: romx_mutable_bundle_entry_info::index"]
        [::std::mem::offset_of!(romx_mutable_bundle_entry_info, index) - 4usize];
    ["Offset of field: romx_mutable_bundle_entry_info::data_size"]
        [::std::mem::offset_of!(romx_mutable_bundle_entry_info, data_size) - 8usize];
    ["Offset of field: romx_mutable_bundle_entry_info::data_crc32"]
        [::std::mem::offset_of!(romx_mutable_bundle_entry_info, data_crc32) - 16usize];
    ["Offset of field: romx_mutable_bundle_entry_info::path_size"]
        [::std::mem::offset_of!(romx_mutable_bundle_entry_info, path_size) - 20usize];
    ["Offset of field: romx_mutable_bundle_entry_info::path"]
        [::std::mem::offset_of!(romx_mutable_bundle_entry_info, path) - 24usize];
};
pub type romx_mutable_bundle_entry_info_t = romx_mutable_bundle_entry_info;
pub type romx_mutable_save_layout_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_save_layout_info {
    pub struct_size: u32,
    pub scope: romx_save_scope_t,
    pub reserved: u16,
    pub flags: romx_mutable_save_layout_flags_t,
    pub entry_count: u32,
    pub extdata_id_size: u32,
    pub extdata_id: [::std::os::raw::c_char; 17usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_mutable_save_layout_info"]
        [::std::mem::size_of::<romx_mutable_save_layout_info>() - 40usize];
    ["Alignment of romx_mutable_save_layout_info"]
        [::std::mem::align_of::<romx_mutable_save_layout_info>() - 4usize];
    ["Offset of field: romx_mutable_save_layout_info::struct_size"]
        [::std::mem::offset_of!(romx_mutable_save_layout_info, struct_size) - 0usize];
    ["Offset of field: romx_mutable_save_layout_info::scope"]
        [::std::mem::offset_of!(romx_mutable_save_layout_info, scope) - 4usize];
    ["Offset of field: romx_mutable_save_layout_info::reserved"]
        [::std::mem::offset_of!(romx_mutable_save_layout_info, reserved) - 6usize];
    ["Offset of field: romx_mutable_save_layout_info::flags"]
        [::std::mem::offset_of!(romx_mutable_save_layout_info, flags) - 8usize];
    ["Offset of field: romx_mutable_save_layout_info::entry_count"]
        [::std::mem::offset_of!(romx_mutable_save_layout_info, entry_count) - 12usize];
    ["Offset of field: romx_mutable_save_layout_info::extdata_id_size"]
        [::std::mem::offset_of!(romx_mutable_save_layout_info, extdata_id_size) - 16usize];
    ["Offset of field: romx_mutable_save_layout_info::extdata_id"]
        [::std::mem::offset_of!(romx_mutable_save_layout_info, extdata_id) - 20usize];
};
pub type romx_mutable_save_layout_info_t = romx_mutable_save_layout_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_save_slot_info {
    pub struct_size: u32,
    pub index: u32,
    pub entry_count: u32,
    pub key_size: u32,
    pub data_size: u64,
    pub display_name_size: u32,
    pub is_directory: u32,
    pub key: [::std::os::raw::c_char; 1025usize],
    pub display_name: [::std::os::raw::c_char; 1025usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_mutable_save_slot_info"]
        [::std::mem::size_of::<romx_mutable_save_slot_info>() - 2088usize];
    ["Alignment of romx_mutable_save_slot_info"]
        [::std::mem::align_of::<romx_mutable_save_slot_info>() - 8usize];
    ["Offset of field: romx_mutable_save_slot_info::struct_size"]
        [::std::mem::offset_of!(romx_mutable_save_slot_info, struct_size) - 0usize];
    ["Offset of field: romx_mutable_save_slot_info::index"]
        [::std::mem::offset_of!(romx_mutable_save_slot_info, index) - 4usize];
    ["Offset of field: romx_mutable_save_slot_info::entry_count"]
        [::std::mem::offset_of!(romx_mutable_save_slot_info, entry_count) - 8usize];
    ["Offset of field: romx_mutable_save_slot_info::key_size"]
        [::std::mem::offset_of!(romx_mutable_save_slot_info, key_size) - 12usize];
    ["Offset of field: romx_mutable_save_slot_info::data_size"]
        [::std::mem::offset_of!(romx_mutable_save_slot_info, data_size) - 16usize];
    ["Offset of field: romx_mutable_save_slot_info::display_name_size"]
        [::std::mem::offset_of!(romx_mutable_save_slot_info, display_name_size) - 24usize];
    ["Offset of field: romx_mutable_save_slot_info::is_directory"]
        [::std::mem::offset_of!(romx_mutable_save_slot_info, is_directory) - 28usize];
    ["Offset of field: romx_mutable_save_slot_info::key"]
        [::std::mem::offset_of!(romx_mutable_save_slot_info, key) - 32usize];
    ["Offset of field: romx_mutable_save_slot_info::display_name"]
        [::std::mem::offset_of!(romx_mutable_save_slot_info, display_name) - 1057usize];
};
pub type romx_mutable_save_slot_info_t = romx_mutable_save_slot_info;
pub type romx_mutable_psp_savedata_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_psp_savedata_info {
    pub struct_size: u32,
    pub flags: romx_mutable_psp_savedata_flags_t,
    pub disc_id: [::std::os::raw::c_char; 65usize],
    pub savedata_directory: [::std::os::raw::c_char; 1025usize],
    pub title: [::std::os::raw::c_char; 1025usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_mutable_psp_savedata_info"]
        [::std::mem::size_of::<romx_mutable_psp_savedata_info>() - 2124usize];
    ["Alignment of romx_mutable_psp_savedata_info"]
        [::std::mem::align_of::<romx_mutable_psp_savedata_info>() - 4usize];
    ["Offset of field: romx_mutable_psp_savedata_info::struct_size"]
        [::std::mem::offset_of!(romx_mutable_psp_savedata_info, struct_size) - 0usize];
    ["Offset of field: romx_mutable_psp_savedata_info::flags"]
        [::std::mem::offset_of!(romx_mutable_psp_savedata_info, flags) - 4usize];
    ["Offset of field: romx_mutable_psp_savedata_info::disc_id"]
        [::std::mem::offset_of!(romx_mutable_psp_savedata_info, disc_id) - 8usize];
    ["Offset of field: romx_mutable_psp_savedata_info::savedata_directory"]
        [::std::mem::offset_of!(romx_mutable_psp_savedata_info, savedata_directory) - 73usize];
    ["Offset of field: romx_mutable_psp_savedata_info::title"]
        [::std::mem::offset_of!(romx_mutable_psp_savedata_info, title) - 1098usize];
};
pub type romx_mutable_psp_savedata_info_t = romx_mutable_psp_savedata_info;
pub type romx_mutable_stats_flags_t = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct romx_mutable_stats {
    pub struct_size: u32,
    pub flags: romx_mutable_stats_flags_t,
    pub play_time_seconds: u64,
    pub launch_count: u64,
    pub first_played_unix_seconds: u64,
    pub last_played_unix_seconds: u64,
    pub favorite: u32,
    pub completed: u32,
    pub completion_percent: u32,
    pub reserved: u32,
    pub achievements_unlocked: u64,
    pub achievements_total: u64,
    pub achievements_hardcore_unlocked: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of romx_mutable_stats"][::std::mem::size_of::<romx_mutable_stats>() - 80usize];
    ["Alignment of romx_mutable_stats"][::std::mem::align_of::<romx_mutable_stats>() - 8usize];
    ["Offset of field: romx_mutable_stats::struct_size"]
        [::std::mem::offset_of!(romx_mutable_stats, struct_size) - 0usize];
    ["Offset of field: romx_mutable_stats::flags"]
        [::std::mem::offset_of!(romx_mutable_stats, flags) - 4usize];
    ["Offset of field: romx_mutable_stats::play_time_seconds"]
        [::std::mem::offset_of!(romx_mutable_stats, play_time_seconds) - 8usize];
    ["Offset of field: romx_mutable_stats::launch_count"]
        [::std::mem::offset_of!(romx_mutable_stats, launch_count) - 16usize];
    ["Offset of field: romx_mutable_stats::first_played_unix_seconds"]
        [::std::mem::offset_of!(romx_mutable_stats, first_played_unix_seconds) - 24usize];
    ["Offset of field: romx_mutable_stats::last_played_unix_seconds"]
        [::std::mem::offset_of!(romx_mutable_stats, last_played_unix_seconds) - 32usize];
    ["Offset of field: romx_mutable_stats::favorite"]
        [::std::mem::offset_of!(romx_mutable_stats, favorite) - 40usize];
    ["Offset of field: romx_mutable_stats::completed"]
        [::std::mem::offset_of!(romx_mutable_stats, completed) - 44usize];
    ["Offset of field: romx_mutable_stats::completion_percent"]
        [::std::mem::offset_of!(romx_mutable_stats, completion_percent) - 48usize];
    ["Offset of field: romx_mutable_stats::reserved"]
        [::std::mem::offset_of!(romx_mutable_stats, reserved) - 52usize];
    ["Offset of field: romx_mutable_stats::achievements_unlocked"]
        [::std::mem::offset_of!(romx_mutable_stats, achievements_unlocked) - 56usize];
    ["Offset of field: romx_mutable_stats::achievements_total"]
        [::std::mem::offset_of!(romx_mutable_stats, achievements_total) - 64usize];
    ["Offset of field: romx_mutable_stats::achievements_hardcore_unlocked"]
        [::std::mem::offset_of!(romx_mutable_stats, achievements_hardcore_unlocked) - 72usize];
};
pub type romx_mutable_stats_t = romx_mutable_stats;
unsafe extern "C" {
    pub fn romx_result_string(result: romx_result_t) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn romx_platform_name(platform_id: u16) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn romx_launch_format_name(launch_format_id: u16) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn romx_file_format_name(format_id: u16) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn romx_platform_status(platform_id: u16) -> romx_registry_status_t;
}
unsafe extern "C" {
    pub fn romx_launch_format_status(launch_format_id: u16) -> romx_registry_status_t;
}
unsafe extern "C" {
    pub fn romx_file_format_status(format_id: u16) -> romx_registry_status_t;
}
unsafe extern "C" {
    pub fn romx_reader_open_path(
        utf8_path: *const ::std::os::raw::c_char,
        options: *const romx_reader_options_t,
        out_reader: *mut *mut romx_reader_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_open_io(
        io: *const romx_io_t,
        options: *const romx_reader_options_t,
        out_reader: *mut *mut romx_reader_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_get_info(
        reader: *const romx_reader_t,
        info: *mut romx_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_get_entry_count(
        reader: *const romx_reader_t,
        count: *mut u32,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_get_entry(
        reader: *const romx_reader_t,
        index: u32,
        entry: *mut romx_entry_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_get_entrypoint(
        reader: *const romx_reader_t,
        entry: *mut romx_entry_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_find_entry(
        reader: *const romx_reader_t,
        virtual_path: *const ::std::os::raw::c_char,
        entry: *mut romx_entry_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_read_entry(
        reader: *const romx_reader_t,
        index: u32,
        entry_offset: u64,
        buffer: *mut ::std::os::raw::c_void,
        buffer_size: u64,
        bytes_read: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_vfs_file_open(
        reader: *const romx_reader_t,
        virtual_path: *const ::std::os::raw::c_char,
        out_file: *mut *mut romx_vfs_file_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_vfs_file_open_entrypoint(
        reader: *const romx_reader_t,
        out_file: *mut *mut romx_vfs_file_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_vfs_file_get_size(
        file: *const romx_vfs_file_t,
        size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_vfs_file_tell(
        file: *const romx_vfs_file_t,
        position: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_vfs_file_seek(
        file: *mut romx_vfs_file_t,
        offset: i64,
        origin: romx_payload_seek_position_t,
        new_position: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_vfs_file_read(
        file: *mut romx_vfs_file_t,
        buffer: *mut ::std::os::raw::c_void,
        size: u64,
        bytes_read: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_vfs_file_close(file: *mut romx_vfs_file_t);
}
unsafe extern "C" {
    pub fn romx_reader_get_mutable_status(
        reader: *const romx_reader_t,
        status: *mut romx_mutable_status_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_get_mutable_object_count(
        reader: *const romx_reader_t,
        count: *mut u32,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_get_mutable_object(
        reader: *const romx_reader_t,
        active_index: u32,
        object: *mut romx_mutable_object_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_find_mutable_object(
        reader: *const romx_reader_t,
        object_namespace: romx_mutable_namespace_t,
        key: *const ::std::os::raw::c_char,
        object: *mut romx_mutable_object_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_file_open(
        reader: *const romx_reader_t,
        object_namespace: romx_mutable_namespace_t,
        key: *const ::std::os::raw::c_char,
        out_file: *mut *mut romx_mutable_file_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_file_get_size(
        file: *const romx_mutable_file_t,
        size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_file_tell(
        file: *const romx_mutable_file_t,
        position: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_file_seek(
        file: *mut romx_mutable_file_t,
        offset: i64,
        origin: romx_payload_seek_position_t,
        new_position: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_file_read(
        file: *mut romx_mutable_file_t,
        buffer: *mut ::std::os::raw::c_void,
        size: u64,
        bytes_read: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_file_close(file: *mut romx_mutable_file_t);
}
unsafe extern "C" {
    pub fn romx_reader_read_region(
        reader: *const romx_reader_t,
        region: romx_region_t,
        region_offset: u64,
        buffer: *mut ::std::os::raw::c_void,
        buffer_size: u64,
        bytes_read: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_get_payload_io(
        reader: *const romx_reader_t,
        out_io: *mut romx_io_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_payload_file_open_path(
        utf8_path: *const ::std::os::raw::c_char,
        reader_options: *const romx_reader_options_t,
        options: *const romx_payload_file_options_t,
        out_file: *mut *mut romx_payload_file_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_payload_file_get_size(
        file: *const romx_payload_file_t,
        size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_payload_file_tell(
        file: *const romx_payload_file_t,
        position: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_payload_file_seek(
        file: *mut romx_payload_file_t,
        offset: i64,
        position: romx_payload_seek_position_t,
        new_position: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_payload_file_read(
        file: *mut romx_payload_file_t,
        buffer: *mut ::std::os::raw::c_void,
        size: u64,
        bytes_read: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_payload_file_close(file: *mut romx_payload_file_t);
}
unsafe extern "C" {
    pub fn romx_reader_map_payload(
        reader: *const romx_reader_t,
        out_mapping: *mut *mut romx_payload_mapping_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_payload_mapping_data(
        mapping: *const romx_payload_mapping_t,
    ) -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn romx_payload_mapping_size(mapping: *const romx_payload_mapping_t) -> u64;
}
unsafe extern "C" {
    pub fn romx_payload_mapping_close(mapping: *mut romx_payload_mapping_t);
}
unsafe extern "C" {
    pub fn romx_reader_copy_region(
        reader: *const romx_reader_t,
        region: romx_region_t,
        sink: *const romx_sink_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_validate(
        reader: *const romx_reader_t,
        flags: romx_validate_flags_t,
        report: *mut romx_validation_report_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_metadata_open(
        reader: *const romx_reader_t,
        out_metadata: *mut *mut romx_metadata_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_metadata_close(metadata: *mut romx_metadata_t);
}
unsafe extern "C" {
    pub fn romx_metadata_copy_json(
        metadata: *const romx_metadata_t,
        buffer: *mut ::std::os::raw::c_void,
        capacity: u64,
        required_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_metadata_get_string(
        metadata: *const romx_metadata_t,
        key: *const ::std::os::raw::c_char,
        buffer: *mut ::std::os::raw::c_char,
        capacity: u64,
        required_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_metadata_get_crc32(
        metadata: *const romx_metadata_t,
        crc32: *mut u32,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_metadata_get_value_json(
        metadata: *const romx_metadata_t,
        key: *const ::std::os::raw::c_char,
        buffer: *mut ::std::os::raw::c_void,
        capacity: u64,
        required_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_extract_payload_path(
        reader: *const romx_reader_t,
        utf8_destination_path: *const ::std::os::raw::c_char,
        options: *const romx_extract_options_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_extract_payload_cache(
        reader: *const romx_reader_t,
        utf8_cache_directory: *const ::std::os::raw::c_char,
        options: *const romx_extract_options_t,
        result_path: *mut ::std::os::raw::c_char,
        result_capacity: u64,
        required_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_get_cover_info(
        reader: *const romx_reader_t,
        info: *mut romx_cover_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_extract_cover_path(
        reader: *const romx_reader_t,
        utf8_destination_path: *const ::std::os::raw::c_char,
        options: *const romx_extract_options_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_writer_write_io_entries(
        utf8_destination_path: *const ::std::os::raw::c_char,
        entries: *const romx_writer_io_entry_t,
        entry_count: u32,
        metadata_json: *const ::std::os::raw::c_void,
        metadata_size: u64,
        cover: *const romx_io_t,
        options: *const romx_writer_options_t,
        report: *mut romx_writer_report_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_writer_write_path_entries(
        utf8_destination_path: *const ::std::os::raw::c_char,
        entries: *const romx_writer_path_entry_t,
        entry_count: u32,
        utf8_metadata_path: *const ::std::os::raw::c_char,
        utf8_cover_path: *const ::std::os::raw::c_char,
        options: *const romx_writer_options_t,
        report: *mut romx_writer_report_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_probe_open_io(
        payload: *const romx_io_t,
        format_hint: u16,
        out_probe: *mut *mut romx_probe_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_probe_open_path(
        utf8_payload_path: *const ::std::os::raw::c_char,
        format_hint: u16,
        out_probe: *mut *mut romx_probe_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_probe_get_info(
        probe: *const romx_probe_t,
        info: *mut romx_probe_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_probe_copy_metadata_json(
        probe: *const romx_probe_t,
        buffer: *mut ::std::os::raw::c_void,
        capacity: u64,
        required_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_probe_copy_cover_png(
        probe: *const romx_probe_t,
        buffer: *mut ::std::os::raw::c_void,
        capacity: u64,
        required_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_probe_close(probe: *mut romx_probe_t);
}
unsafe extern "C" {
    pub fn romx_mutable_write_io_path(
        utf8_romx_path: *const ::std::os::raw::c_char,
        object_namespace: romx_mutable_namespace_t,
        key: *const ::std::os::raw::c_char,
        source: *const romx_io_t,
        options: *const romx_mutable_write_options_t,
        written_object: *mut romx_mutable_object_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_write_path(
        utf8_romx_path: *const ::std::os::raw::c_char,
        object_namespace: romx_mutable_namespace_t,
        key: *const ::std::os::raw::c_char,
        utf8_source_path: *const ::std::os::raw::c_char,
        options: *const romx_mutable_write_options_t,
        written_object: *mut romx_mutable_object_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_measure_path_entries(
        object_namespace: romx_mutable_namespace_t,
        entries: *const romx_mutable_bundle_path_entry_t,
        entry_count: u32,
        bundle_options: *const romx_mutable_bundle_options_t,
        serialized_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_copy_region_path(
        utf8_source_romx_path: *const ::std::os::raw::c_char,
        utf8_destination_romx_path: *const ::std::os::raw::c_char,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_delete_path(
        utf8_romx_path: *const ::std::os::raw::c_char,
        object_namespace: romx_mutable_namespace_t,
        key: *const ::std::os::raw::c_char,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_write_path_entries(
        utf8_romx_path: *const ::std::os::raw::c_char,
        object_namespace: romx_mutable_namespace_t,
        key: *const ::std::os::raw::c_char,
        entries: *const romx_mutable_bundle_path_entry_t,
        entry_count: u32,
        bundle_options: *const romx_mutable_bundle_options_t,
        write_options: *const romx_mutable_write_options_t,
        written_object: *mut romx_mutable_object_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_profile_get(
        platform_id: u16,
        format_id: u16,
        launch_format_id: u16,
        profile: *mut romx_save_profile_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_open_path(
        utf8_source_path: *const ::std::os::raw::c_char,
        options: *const romx_save_scan_options_t,
        out_catalog: *mut *mut romx_save_catalog_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_get_profile(
        catalog: *const romx_save_catalog_t,
        profile: *mut romx_save_profile_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_get_candidate_count(
        catalog: *const romx_save_catalog_t,
        count: *mut u32,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_get_candidate(
        catalog: *const romx_save_catalog_t,
        index: u32,
        candidate: *mut romx_save_candidate_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_get_file_count(
        catalog: *const romx_save_catalog_t,
        candidate_index: u32,
        count: *mut u32,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_get_file(
        catalog: *const romx_save_catalog_t,
        candidate_index: u32,
        file_index: u32,
        file: *mut romx_save_file_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_copy_candidate_source_path(
        catalog: *const romx_save_catalog_t,
        candidate_index: u32,
        buffer: *mut ::std::os::raw::c_void,
        capacity: u64,
        required_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_measure_candidate(
        catalog: *const romx_save_catalog_t,
        candidate_index: u32,
        bundle_options: *const romx_mutable_bundle_options_t,
        serialized_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_write_candidate(
        catalog: *const romx_save_catalog_t,
        candidate_index: u32,
        utf8_romx_path: *const ::std::os::raw::c_char,
        object_key: *const ::std::os::raw::c_char,
        bundle_options: *const romx_mutable_bundle_options_t,
        write_options: *const romx_mutable_write_options_t,
        written_object: *mut romx_mutable_object_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_save_catalog_close(catalog: *mut romx_save_catalog_t);
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_open(
        reader: *const romx_reader_t,
        object_namespace: romx_mutable_namespace_t,
        key: *const ::std::os::raw::c_char,
        options: *const romx_mutable_bundle_options_t,
        out_bundle: *mut *mut romx_mutable_bundle_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_get_entry_count(
        bundle: *const romx_mutable_bundle_t,
        count: *mut u32,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_get_entry(
        bundle: *const romx_mutable_bundle_t,
        index: u32,
        entry: *mut romx_mutable_bundle_entry_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_get_save_layout(
        bundle: *const romx_mutable_bundle_t,
        layout: *mut romx_mutable_save_layout_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_get_save_slot_count(
        bundle: *const romx_mutable_bundle_t,
        count: *mut u32,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_get_save_slot(
        bundle: *const romx_mutable_bundle_t,
        index: u32,
        slot: *mut romx_mutable_save_slot_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_get_save_slot_entry(
        bundle: *const romx_mutable_bundle_t,
        slot_index: u32,
        entry_index: u32,
        entry: *mut romx_mutable_bundle_entry_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_psp_savedata_inspect_sfo(
        sfo_bytes: *const ::std::os::raw::c_void,
        sfo_size: u64,
        expected_directory_basename: *const ::std::os::raw::c_char,
        info: *mut romx_mutable_psp_savedata_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_read_entry(
        bundle: *mut romx_mutable_bundle_t,
        index: u32,
        entry_offset: u64,
        buffer: *mut ::std::os::raw::c_void,
        buffer_size: u64,
        bytes_read: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_bundle_close(bundle: *mut romx_mutable_bundle_t);
}
unsafe extern "C" {
    pub fn romx_mutable_stats_parse_json(
        json: *const ::std::os::raw::c_void,
        json_size: u64,
        stats: *mut romx_mutable_stats_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_stats_merge_session_delta(
        baseline: *const romx_mutable_stats_t,
        session_delta: *const romx_mutable_stats_t,
        merged: *mut romx_mutable_stats_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_stats_serialize_json(
        stats: *const romx_mutable_stats_t,
        buffer: *mut ::std::os::raw::c_void,
        capacity: u64,
        required_size: *mut u64,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_stats_read(
        reader: *const romx_reader_t,
        key: *const ::std::os::raw::c_char,
        stats: *mut romx_mutable_stats_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_mutable_stats_write_path(
        utf8_romx_path: *const ::std::os::raw::c_char,
        key: *const ::std::os::raw::c_char,
        stats: *const romx_mutable_stats_t,
        options: *const romx_mutable_write_options_t,
        written_object: *mut romx_mutable_object_info_t,
        error: *mut romx_error_t,
    ) -> romx_result_t;
}
unsafe extern "C" {
    pub fn romx_reader_close(reader: *mut romx_reader_t);
}
